### ISSUE TITLE
I tried to generate scenarios using GeometricBrownianMotion: Throws an Error

### ISSUE THREAD

**Issue by shivapower1985** [jason-ash/pyesg#60]
Hi Jason,
I am Shiva and I am working on scenario generation on solar PV generation forecast to address uncertainty between the actual and prediction.

I tried to use "pyesg" - Geometric Brownian Motion to generate scenerios.

I am using google colab environment for my research work and I installed the package using "!pip install pyesg"

I tried your example in my google colab space and it throws error. Please advice me to solve the issue.

I have attached screen shot below,

![image](https://user-images.githubusercontent.com/50398806/82969340-0f3ddf00-9fed-11ea-8994-013950cb1a55.png)

**Comment by jason-ash** [comment]
Thanks for flagging this! The latest version of pyesg, which works with the example you posted, hasn’t been pushed to PyPI yet. So pip install pyesg is pulling an older version. I intend to update this tomorrow, so please check back and I believe your issue will be solved.

**Comment by jason-ash** [comment]
Out of curiosity, I’m always looking for feedback on how people may want to use this library. Care to share what you’re trying to accomplish?

**Comment by jason-ash** [comment]
@shivapower1985, there's a new version on PyPI now. Would you try your code again and let me know if you have the same issue?

**Comment by shivapower1985** [comment]
> @shivapower1985, there's a new version on PyPI now. Would you try your code again and let me know if you have the same issue?


Thank you Jason I worked with the new version and it works fine and it had solved my problem.

**Comment by jason-ash** [comment]
Great!

**Comment by shivapower1985** [comment]
> Out of curiosity, I’m always looking for feedback on how people may want to use this library. Care to share what you’re trying to accomplish?

Jason, 
I work on forecasting solar PV output power from photovoltaic plant and also developing optimization algorithm for optimal battery charging and discharging settings. The problem is interlinked where the accuracy battery optimization algorithm depends on forecasting solar PV module. Meaning if the accuracy of solar PV forecasting is high the battery charging/discharging setting is very good and vice-versa. 
Now I have to build a accurate solar PV forecasting module on the other hand it is very challenging to match the uncertainty between "Predicted" and "True" as the vital parameters are weather dependent.  

* What I do to address this uncertainty?
To address this uncertainty in my model I build a prediction interval (PI) band having [lower bound, upper bound] across the forecasted values considering that the Actual or True value will fall between the PI band. Then I will have to follow up Scenario Generation and Scenario Reduction procedures. 

* Here is where I use your scenerio generation package.
I use "GeometricBrownianMotion" from your "pyesg" package to generate 1000 scenarios between the PI band and this looks like this,
![image](https://user-images.githubusercontent.com/50398806/83089543-285d9300-a0b4-11ea-8bab-4d352072f195.png)

* Scenario reduction technique to be followed after scenario generation.
Now 1000 scenarios are generated and a reduction technique or procedure will be followed to select top 5 scenarios based on probability. 
Top 5 highly probable scenarios are selected and for which I shall perform optimization algorithm to arrive optimal battery charging/discharging references.


Shiva

**Comment by shivapower1985** [comment]
Jason, 

Have you worked on probability based scenario reduction techniques in python. You may suggest me some packages for it.

Shiva

**Comment by jason-ash** [comment]
Scenario reduction is on a list of potential features I'm considering. I'm not aware of other packages to recommend, sorry.
