### ISSUE TITLE
doc for GBM

### ISSUE THREAD

**Issue by liyi-1989** [jason-ash/pyesg#73]
One question,

https://github.com/jason-ash/pyesg/blob/c364ebb641c33641bfeb92b1a7e53137ef1a5ad2/pyesg/processes/geometric_brownian_motion.py#L10

Looks like you are trying to apply sth like eq(7) of http://www.frouah.com/finance%20notes/Euler%20and%20Milstein%20Discretization.pdf?
If so, the formula of GBM (that you are using in the code) maybe sth like:
Geometric Brownian Motion: X_{k+1} = X_k*exp((μ - δ - (1/2)*σ**2)dt + σdW)?

And do you have any suggested documentation for the Euler scheme you are using (like what is the apply function, etc)? 

Thanks!

**Comment by jason-ash** [comment]
Thanks for the question! I've been using [Hull White](https://www.amazon.com/Options-Futures-Other-Derivatives-9th/dp/0133456315) as one of the main sources for formulas, documentation, etc.

I realized there is a typo in the documentation you linked. I forgot to add `dt ** 0.5` in the random noise term, and I think this may need to be corrected in the `_diffusion` method as well. I will write up a quick fix for this. Thanks again for catching it!

**Comment by liyi-1989** [comment]
Thank you very much!
