### ISSUE TITLE
Skewness feature?

### ISSUE THREAD

**Issue by hotakkwan** [jason-ash/pyesg#90]
I found this package when asking Cursor about esg models that can generate customized skewness stock returns, it responded:

`from pyesg import ESG

params = {
    'n_scenarios': 1000,
    'n_years': 10,
    'dt': 1/12,
    'r0': 0.02,
    'vol': 0.01,
    'mean_reversion': 0.1,
    'lambda_': 0.1,
    'sigma': 0.01,
    'rho': 0.5,
    'skew': -0.5
}
esg = ESG('GBM', params)
`

Looks like in some version, this package can generate GBM with customized skewness, but I could not find it in the current version.

Is there any solution?

**Comment by jason-ash** [comment]
I think the LLM may have hallucinated the API you described :). Sorry, but that feature isn't something that exists, although as an open source library, you are more than welcome to submit a pull request that adds this functionality. I'd be happy to help!
